// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkosgoxwtwrjxhghnbhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrb3Nnb3h3dHdyanhoZ2huYmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzgwODUsImV4cCI6MjA2NDQ1NDA4NX0.kePfxLlrhzF17bykYZVEsVT6nbZ3VJ1Oid6_EgX-UqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);